[build]
  bin = "./bin/app-salud-back"
  cmd = "go build -o ./bin/app-salud-back ./cmd"
  dir = "."
  include_ext = ["go"]
  delay = 1000
  exclude_dir = ["bin", "vendor"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  level = "debug"
